version: "2.1"

services:
  server:
    build: Server
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_HOST=db
      - DB_SCHEMA=matohmat
      - DB_USER=matomat_system
      - DB_PWD=password_here
      - DEVICE_KEYS=device_keys.txt
      - ORIGINS=http://localhost:8080::null
    restart: always
  db:
    build: Database
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ${PWD}/data:/var/lib/mysql
    restart: always

