version: "2.1"

services:
  proxy:
    image: nginx:1.15.12
    ports:
       - "127.0.0.1:8080:8080"
    volumes:
      - "./proxy:/etc/nginx/conf.d"
    restart: always
    depends_on:
      - matohmat
      - filebrowser
  matohmat:
    build: Server
    depends_on:
      - db
    environment:
      - PARAM=
      - CONFIG_FILE=server.conf
    restart: always
    volumes:
      - ./Server/device_keys.txt:/home/device_keys.txt
      - ./Server/server.conf:/home/server.conf
  db:
    build: Database
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    restart: always
  filebrowser:
    image: filebrowser/filebrowser:v2.0.12
    volumes:
      - ./filebrowser/data:/srv
      - ./filebrowser/filebrowser.json:/.filebrowser.json
      - ./filebrowser/db:/db

