version: "2.1"

services:
  matohmat:
    build: matohmat
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    environment:
      - PARAM=
      - CONFIG_FILE=server.conf
    restart: always
    volumes:
      - ./matohmat/device_keys.txt:/home/device_keys.txt
      - ./matohmat/server.conf:/home/server.conf
      - ./matohmat/mail_template.txt:/home/mail_template.txt
  db:
    build: Database
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    restart: always 
